server:
  address:     ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/redoc"
  graceful: true
  gracefulTimeout: 5

# 文件上传设置
upload:
  path: "resource/upload"

logger:
  level : "all"
  stdout: true



