// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ChannelGroup is the golang structure of table channel_group for DAO operations like Where/Data.
type ChannelGroup struct {
	g.Meta  `orm:"table:channel_group, do:true"`
	Id      interface{} //
	Channel interface{} //
	Group   interface{} //
}
