// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigGroup is the golang structure of table config_group for DAO operations like Where/Data.
type ConfigGroup struct {
	g.Meta    `orm:"table:config_group, do:true"`
	GroupId   interface{} //
	GroupName interface{} //
}
