// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigFight is the golang structure of table config_fight for DAO operations like Where/Data.
type ConfigFight struct {
	g.Meta  `orm:"table:config_fight, do:true"`
	Id      interface{} // 渠道组id(引用mst_channel_group表中的group_id)
	GroupId interface{} //
	Name    interface{} // 战斗服名
	Host    interface{} // 主机ip
	Port    interface{} // websocket端口
}
