// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigZone is the golang structure of table config_zone for DAO operations like Where/Data.
type ConfigZone struct {
	g.Meta           `orm:"table:config_zone, do:true"`
	ZoneId           interface{} // 区号
	GroupId          interface{} //
	ZoneName         interface{} // 区名称
	Host             interface{} // 主机ip
	HostOut          interface{} //
	WebsocketPort    interface{} // websocket端口
	WebsocketPortOut interface{} //
	HttpPort         interface{} // http端口
	AdminPort        interface{} // 管理接口端口
	AdminPortOut     interface{} //
	Status           interface{} // 状态(0、测试服 1、正式服)
	OpenTime         *gtime.Time // 开放时间
	MaxSize          interface{} // 最大注册人数
	MaxOnlineSize    interface{} // 最大在线人数
	OpenStatus       interface{} // 0、新 1、热
	DisplayOrder     interface{} //
}
