// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigGroupChannel is the golang structure of table config_group_channel for DAO operations like Where/Data.
type ConfigGroupChannel struct {
	g.Meta    `orm:"table:config_group_channel, do:true"`
	Id        interface{} //
	GroupId   interface{} // 分组ID
	ChannelId interface{} // 组名称
}
