// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigChannel is the golang structure of table config_channel for DAO operations like Where/Data.
type ConfigChannel struct {
	g.Meta      `orm:"table:config_channel, do:true"`
	ChannelId   interface{} //
	ChannelName interface{} // 渠道名称
	Version     interface{} //
}
