// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigResDb is the golang structure of table config_res_db for DAO operations like Where/Data.
type ConfigResDb struct {
	g.Meta   `orm:"table:config_res_db, do:true"`
	ZoneId   interface{} // 区id(引用mst_zone中的zone_id,0表示所有的区)
	UserName interface{} // 资源库用户名
	Password interface{} // 资源库密码
	Url      interface{} // 连接字符串
	Driver   interface{} // DB驱动程序
}
