// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Server is the golang structure of table server for DAO operations like Where/Data.
type Server struct {
	g.Meta    `orm:"table:server, do:true"`
	Id        interface{} //
	Group     interface{} //
	Name      interface{} //
	Ip        interface{} //
	Http      interface{} //
	Socket    interface{} //
	MaxReg    interface{} //
	MaxOnline interface{} //
	Status    interface{} //
	Hot       interface{} //
	Sort      interface{} //
	Open      *gtime.Time //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
