// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigFightDao is the data access object for table config_fight.
type ConfigFightDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns ConfigFightColumns // columns contains all the column names of Table for convenient usage.
}

// ConfigFightColumns defines and stores column names for table config_fight.
type ConfigFightColumns struct {
	Id      string // 渠道组id(引用mst_channel_group表中的group_id)
	GroupId string //
	Name    string // 战斗服名
	Host    string // 主机ip
	Port    string // websocket端口
}

// configFightColumns holds the columns for table config_fight.
var configFightColumns = ConfigFightColumns{
	Id:      "id",
	GroupId: "group_id",
	Name:    "name",
	Host:    "host",
	Port:    "port",
}

// NewConfigFightDao creates and returns a new DAO object for table data access.
func NewConfigFightDao() *ConfigFightDao {
	return &ConfigFightDao{
		group:   "default",
		table:   "config_fight",
		columns: configFightColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ConfigFightDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ConfigFightDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ConfigFightDao) Columns() ConfigFightColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ConfigFightDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ConfigFightDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ConfigFightDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
