
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "main"
    path: "./bin"
    arch: "amd64"
    system: "linux"
    packSrc: "resource,manifest/config"