
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "gof"
    path: "bin"
    arch: "amd64"
    system: "linux"
    packSrc: "resource,manifest"

database:
  default:
    - link: "mysql:root:@tcp(192.168.51.229:3306)/gof"
      jsonCase: "Snake"