
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "main"
#    path: "./bin"
#    arch: "amd64"
#    system: "linux"
    packSrc: "hack,manifest/config"

database:
  default:
    link: "mysql:root:@tcp(127.0.0.1:3306)/mgxx_server"