// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/internal/dao/internal"
)

// internalChannelGroupDao is internal type for wrapping internal DAO implements.
type internalChannelGroupDao = *internal.ChannelGroupDao

// channelGroupDao is the data access object for table channel_group.
// You can define custom methods on it to extend its functionality as you wish.
type channelGroupDao struct {
	internalChannelGroupDao
}

var (
	// ChannelGroup is globally public accessible object for table channel_group operations.
	ChannelGroup = channelGroupDao{
		internal.NewChannelGroupDao(),
	}
)

// Fill with you ideas below.
