// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/internal/dao/internal"
)

// internalConfigDataDbDao is internal type for wrapping internal DAO implements.
type internalConfigDataDbDao = *internal.ConfigDataDbDao

// configDataDbDao is the data access object for table config_data_db.
// You can define custom methods on it to extend its functionality as you wish.
type configDataDbDao struct {
	internalConfigDataDbDao
}

var (
	// ConfigDataDb is globally public accessible object for table config_data_db operations.
	ConfigDataDb = configDataDbDao{
		internal.NewConfigDataDbDao(),
	}
)

// Fill with you ideas below.
