// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/internal/dao/internal"
)

// internalConfigGroupDao is internal type for wrapping internal DAO implements.
type internalConfigGroupDao = *internal.ConfigGroupDao

// configGroupDao is the data access object for table config_group.
// You can define custom methods on it to extend its functionality as you wish.
type configGroupDao struct {
	internalConfigGroupDao
}

var (
	// ConfigGroup is globally public accessible object for table config_group operations.
	ConfigGroup = configGroupDao{
		internal.NewConfigGroupDao(),
	}
)

// Fill with you ideas below.
