// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/internal/dao/internal"
)

// internalConfigZoneDao is internal type for wrapping internal DAO implements.
type internalConfigZoneDao = *internal.ConfigZoneDao

// configZoneDao is the data access object for table config_zone.
// You can define custom methods on it to extend its functionality as you wish.
type configZoneDao struct {
	internalConfigZoneDao
}

var (
	// ConfigZone is globally public accessible object for table config_zone operations.
	ConfigZone = configZoneDao{
		internal.NewConfigZoneDao(),
	}
)

// Fill with you ideas below.
