// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ChannelGroup is the golang structure for table channel_group.
type ChannelGroup struct {
	Id      uint   `json:"id"      ` //
	Channel string `json:"channel" ` //
	Group   uint   `json:"group"   ` //
}
