// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigGroup is the golang structure for table config_group.
type ConfigGroup struct {
	GroupId   int    `json:"groupId"   ` //
	GroupName string `json:"groupName" ` //
}
