// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigDataDb is the golang structure for table config_data_db.
type ConfigDataDb struct {
	ZoneId     int    `json:"zoneId"     ` // 区id(引用mst_zone中的zone_id,0表示所有的区)
	UserName   string `json:"userName"   ` // 数据库用户名
	Password   string `json:"password"   ` // 数据库密码
	DbName     string `json:"dbName"     ` // 数据库名称
	MasterHost string `json:"masterHost" ` // 主库ip
	MasterPort int    `json:"masterPort" ` // 主库端口
	SlaveHost  string `json:"slaveHost"  ` // 从库ip
	SlavePort  int    `json:"slavePort"  ` // 从库端口
}
