// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigFight is the golang structure for table config_fight.
type ConfigFight struct {
	Id      int    `json:"id"      ` // 渠道组id(引用mst_channel_group表中的group_id)
	GroupId int    `json:"groupId" ` //
	Name    string `json:"name"    ` // 战斗服名
	Host    string `json:"host"    ` // 主机ip
	Port    int    `json:"port"    ` // websocket端口
}
