// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ConfigZone is the golang structure for table config_zone.
type ConfigZone struct {
	ZoneId           int         `json:"zoneId"           ` // 区号
	GroupId          int         `json:"groupId"          ` //
	ZoneName         string      `json:"zoneName"         ` // 区名称
	Host             string      `json:"host"             ` // 主机ip
	HostOut          string      `json:"hostOut"          ` //
	WebsocketPort    int         `json:"websocketPort"    ` // websocket端口
	WebsocketPortOut int         `json:"websocketPortOut" ` //
	HttpPort         int         `json:"httpPort"         ` // http端口
	AdminPort        int         `json:"adminPort"        ` // 管理接口端口
	AdminPortOut     int         `json:"adminPortOut"     ` //
	Status           int         `json:"status"           ` // 状态(0、测试服 1、正式服)
	OpenTime         *gtime.Time `json:"openTime"         ` // 开放时间
	MaxSize          int         `json:"maxSize"          ` // 最大注册人数
	MaxOnlineSize    int         `json:"maxOnlineSize"    ` // 最大在线人数
	OpenStatus       int         `json:"openStatus"       ` // 0、新 1、热
	DisplayOrder     int         `json:"displayOrder"     ` //
}
