// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigGroupChannel is the golang structure for table config_group_channel.
type ConfigGroupChannel struct {
	Id        int `json:"id"        ` //
	GroupId   int `json:"groupId"   ` // 分组ID
	ChannelId int `json:"channelId" ` // 组名称
}
