// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigChannel is the golang structure for table config_channel.
type ConfigChannel struct {
	ChannelId   int    `json:"channelId"   ` //
	ChannelName string `json:"channelName" ` // 渠道名称
	Version     int    `json:"version"     ` //
}
