// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Server is the golang structure for table server.
type Server struct {
	Id        uint        `json:"id"        ` //
	Group     uint        `json:"group"     ` //
	Name      string      `json:"name"      ` //
	Ip        string      `json:"ip"        ` //
	Http      string      `json:"http"      ` //
	Socket    string      `json:"socket"    ` //
	MaxReg    uint        `json:"maxReg"    ` //
	MaxOnline uint        `json:"maxOnline" ` //
	Status    int         `json:"status"    ` //
	Hot       int         `json:"hot"       ` //
	Sort      uint        `json:"sort"      ` //
	Open      *gtime.Time `json:"open"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
}
