// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        uint        `json:"id"        ` //
	Passport  string      `json:"passport"  ` //
	Password  string      `json:"password"  ` //
	Nickname  string      `json:"nickname"  ` //
	Avatar    string      `json:"avatar"    ` //
	Playerids string      `json:"playerids" ` //
	Email     string      `json:"email"     ` //
	Phone     uint        `json:"phone"     ` //
	Channel   uint        `json:"channel"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
}
